spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type: trace
    org.hibernate.stat: debug
